### ISSUE TITLE
Cannot run on versions 4.11.3 & 4.11.4

### ISSUE THREAD

**Issue by WebShapedBiz** [DomDew/strapi-plugin-fuzzy-search#83]
I have a year-old app constantly updated, now up to Strapi v4.11.2 and fuzzy-search v1.9.4
After updating Strapi to 4.11.3 and 4.11.4, `npm run build` runs fine but `npm run develop` produces this error:
`Error: Could not load js config file /home/xxxx/Dev/yyyy/strapi/node_modules/strapi-plugin-fuzzy-search/strapi-server.js: Cannot find module '@strapi/utils/lib/errors'`
Updating fuzzy-search to the latest version didn't help.

I made a clean new Strapi installation, installing only the `strapi-plugin-fuzzy-search` plugin afterwards and the same error appeared, so it's reproducible.

Removing this plugin enabled me to run my app again.

**Comment by amityweb** [comment]
Yep got it today. I temporarily fixed it by changing the following:

**dist/server/utils/validateQuery.js**
Change require("@strapi/utils/lib/errors") to require("@strapi/utils").errors

**dist/server/controllers/search-controller.js**
Change require("@strapi/utils/lib/errors") to require("@strapi/utils").errors

**dist/server/utils/sanitizeOutput.js**
Change require("@strapi/utils/lib/sanitize") to require("@strapi/utils").sanitize


require("@strapi/utils/lib/sanitize");

**Comment by dioteos** [comment]
I also have this issue
The fix I'm currently using on my dev environment is specifying the dependency to "@strapi/utils" explicitly. 

I can confirm the working setup:
```
"@strapi/strapi": "4.11.4",
"strapi-plugin-fuzzy-search": "^1.11.0",
"@strapi/utils": "4.11.0",
```

**Comment by joshacross** [comment]
Hello any update on this? The fixes above are not working for me

**Comment by darokviana** [comment]
As the plugin is a crucial part of my application, I had to downgrade Strapi to version 4.10.5. Waiting for the resolution of the version conflict.

**Comment by dschi** [comment]
I helped myself with [patch-package](https://github.com/ds300/patch-package). Its very simple to setup and can easily be removed once the issue is fixed. 
Apply the changes from this [post](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/83#issuecomment-1623563252).

**Comment by joshacross** [comment]
Thank you for the quick replies. At first downgrading did not seem to work, but then I used the command `npm i strapi-plugin-fuzzy-search --legacy-peer-deps`, and it installed without any issues. Then ran build and voilá! It works again! I will keep you posted if I run into any further difficulties.

**Comment by joshacross** [comment]
I was going to submit this question to rfcs, but that I would ask it here before I do...

Can you target the specific `strapi-plugin-fuzzy-search` package using a `.npmrc` file? 

Knowing I was able to temporarily resolve the conflicting peer dependency issue above by added the `--legacy-peer-deps` flag after installing `strapi-plugin-fuzzy-search`, I added a .npmrc file to my root directory with `legacy-peer-deps=true`. 

[Per config | npm docs: ](https://docs.npmjs.com/cli/v9/using-npm/config#legacy-peer-deps )

_"Causes npm to completely ignore peerDependencies when building a package tree, as in npm versions 3 through 6.

If a package cannot be installed because of overly strict peerDependencies that collide, it provides a way to move forward resolving the situation.

This differs from --omit=peer, in that --omit=peer will avoid unpacking peerDependencies on disk, but will still design a tree such that peerDependencies could be unpacked in a correct place.

Use of legacy-peer-deps is not recommended, as it will not enforce the peerDependencies contract that meta-dependencies may rely on."_

However, adding this to the .npmrc file applies the flag to all installs not just the strapi-plugin-fuzzy-search. So I am wondering, is there a cli command that is able to mitigate this?

**Comment by DomDew** [comment]
Hey everyone.

Should be fixed in `v2.0.4` and `v1.11.3` respectively. Note that these versions require you to run on a Strapi version `>= 4.11.4`, as Strapi published a breaking change to the way they organize imports from their utils.

Note that you will have probably have to run an `npm ci` to generate fresh node_modules.

Please let me know if things still aren't working as expected.
